name: Deploy API to VM

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'docker-compose.yml'
      - 'Dockerfile'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/yapwrap
            git pull origin main
            sudo docker compose up --build -d
            sudo docker image prune -f